### ISSUE TITLE
Bootstrapping support

### ISSUE THREAD

**Issue by matbeale** [alexwailan/rpinecone#10]
Hi guys,

I've been trying to understand some of the quirks of the method, since I have parts of a tree with low bootstrap support, and this leads to variable pinecone clusters in this region. In the bootstrap supplement Gerry uploaded, he loops rPinecone over 100 bootstrap trees, and then clusters them with `hclust`, then cut the tree using `cutree`. I'm trying to understand the effect of that. I think that `cutree(h, h = 5)` means you discard anything that isn't in at least 5 bootstraps - is that correct? If I wanted to use the best supported clusters (e.g. in >80% of trees), I would therefore use `cutree(h, h = 80)` - is that right?

Many thanks,
Mat

**Comment by gtonkinhill** [comment]
Hi Mat,

Nearly, it's been a while since I've looked at this but I think the height refers to the maximum percentage of trees that do not have that clustering. Thus for >80% of trees you would use `cutree(h, h=20)`.  i.e. larger heights are more inclusive.

It might be worth double checking this as I haven't run the code for quite a while.

**Comment by matbeale** [comment]
Thanks Gerry, 
That's what has me confused. Decreasing the `h` cuttoff seems to result in _more_ clusters, and these are less well defined, as shown in your illustrative plot from the vignette. 

I've used the same basic code in the attached (where h=5 is labelled 95%, h=20 is labelled 80%, etc): 

![image](https://user-images.githubusercontent.com/16351605/106300476-75e75c80-624e-11eb-9d11-8acccd2d4de0.png)

As you can see, with a low `h` value e.g. 5 (95%), the clustering becomes highly fragmented. What I actually want is to be able to keep the best supported clusters. Perhaps I'm misunderstanding...?

Best Wishes,
Mat

**Comment by gtonkinhill** [comment]
Hi Mat,

I think this is expected. As you place stricter thresholds on the support required for a cluster, fewer large clusters will meet the requirement and thus you will end up with a more fragmented set of smaller but highly supported clusters. This looks like there isn't strong support for the larger clusters using the rpinecone approach.

Thus smaller h will result in smaller clusters with stronger support.

**Comment by matbeale** [comment]
Thanks Gerry. As discussed outside of github, my main interest is in obtaining the most stable cluster assignments - i.e. sacrificing sensitivity for robustness. As such, I'm willing to take the hit on finescale discrimination here, and use the 5% clusters. Thanks for your help
